version: '3.1'

services:

  wordpress:
    image: wordpress:6.0
    restart: always
    ports:
      - 8080:80 # use 8080 port on your host to get access to wordpress
    environment: # can keep it the way it is, db would not be opened to the public
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wpfile:/var/www/html # use ./wpfile to store the your wordpress file
    networks:
      - mynetwork # let containers share the same network so they can communicate
  db:
    image: mysql:8.0
    restart: always
    environment: # can keep it the way it is, db would not be opened to the public
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./dbfile:/var/lib/mysql # store mysql data
    networks:
      - mynetwork
  
networks:
  mynetwork:
    driver: bridge
